# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17GFcCtGP5QGcCO6LjF0d-C8WfrjP_w7I

01 PROJETO DE ANALISE DE DADOS - EBAC

Com os dados fornecidos nosso objetivo é analisar os mesmos para identificar padrões, problemas e oportunidades de melhoria.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Carregar os dados do JSON
url = 'https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/dataset/deliveries.json'
df = pd.read_json(url)

# Expandir a coluna 'deliveries' em um DataFrame separado
deliveries = df['deliveries'].explode().apply(pd.Series)

# Verificar as primeiras linhas do DataFrame expandido
print(deliveries.head())

# Calcular a capacidade total dos veículos por região
total_capacity_by_region = df.groupby('region')['vehicle_capacity'].sum()

# Mostrar a capacidade total dos veículos por região
print(total_capacity_by_region)

# Contar o número de entregas feitas por região
deliveries_count_by_region = deliveries.groupby(df['region']).size()

# Mostrar a quantidade de entregas por região
print(deliveries_count_by_region)

# Visualização da capacidade total dos veículos por região
plt.figure(figsize=(12, 6))
total_capacity_by_region.plot(kind='bar', color='skyblue')
plt.title('Capacidade Total dos Veículos por Região')
plt.xlabel('Região')
plt.ylabel('Capacidade Total')
plt.xticks(rotation=0)
plt.show()

# Visualização da quantidade de entregas por região
plt.figure(figsize=(12, 6))
deliveries_count_by_region.plot(kind='bar', color='lightgreen')
plt.title('Quantidade de Entregas por Região')
plt.xlabel('Região')
plt.ylabel('Quantidade de Entregas')
plt.xticks(rotation=0)
plt.show()

"""    Análise Exploratória dos Dados de Entregas de Logística

Nesta análise, exploramos um conjunto de dados de entregas logísticas para entender melhor a distribuição da capacidade dos veículos e o número de entregas por região.

    Capacidade dos Veículos por Região

Observamos que a capacidade total dos veículos varia significativamente de uma região para outra. As regiões mais populosas ou com maior demanda logística podem requerer veículos com maior capacidade para atender à demanda. Isso pode indicar uma correlação entre a densidade populacional ou a atividade econômica de uma região e a capacidade necessária dos veículos de entrega.

    Número de Entregas por Região

Ao analisar o número de entregas por região, observamos padrões interessantes. Algumas regiões podem ter um volume maior de entregas devido à sua localização estratégica, à presença de centros comerciais ou industriais, ou à densidade populacional. Por outro lado, regiões menos desenvolvidas podem ter um número menor de entregas, refletindo uma menor demanda logística.

     Insights e Considerações

Otimização de Rotas: Compreender a distribuição da capacidade dos veículos e o volume de entregas por região pode ajudar as empresas de logística a otimizar suas rotas de entrega, alocar recursos de forma mais eficiente e reduzir custos operacionais.

Expansão de Mercado: Identificar regiões com alto potencial de crescimento no número de entregas pode orientar as estratégias de expansão de mercado das empresas de logística. Investir em regiões com crescimento significativo na demanda por entregas pode resultar em um aumento da participação de mercado e maior lucratividade.

Sazonalidade: É importante considerar a sazonalidade ao analisar o volume de entregas por região. Algumas regiões podem experimentar picos de demanda durante determinadas épocas do ano, como feriados ou eventos sazonais. Essa sazonalidade deve ser levada em conta ao planejar as operações logísticas.

     Conclusão

Esta análise exploratória fornece insights valiosos sobre a distribuição da capacidade dos veículos e o volume de entregas por região. Compreender esses padrões pode ajudar as empresas de logística a tomar decisões mais informadas e eficazes, melhorando a eficiência operacional e impulsionando o crescimento do negócio.







"""